name: Build Test
on:
  # Build PRs and branches.
  pull_request:
    # TODO: Uncomment this before merging.
    #paths-ignore:
    #  - .github/workflows/deploy-tagged.yml
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - .github/workflows/deploy-tagged.yml

jobs:
  build:
    name: jdk ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://en.wikipedia.org/wiki/Java_version_history
        java: [ '8', '11' ] # LTS

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven' # automatic cache

      - name: Test
        run: mvn -B clean test
